name: UHC
version: 1.0.2
author: Neyuux_
main: fr.neyuux.uhc.UHC
softdepend: [NeyGin_Core]
load: STARTUP
commands:
  uhc:
    description: Commande Principale
  revive:
    description: Commande de Revive
    permission: uhc.host
    permission-message: §e§lUHC §7>> §cVous devez être host pour utiliser cette commande.
  heal:
    description: Commande de Final Heal
    permission: uhc.host
    permission-message: §e§lUHC §7>> §cVous devez être host pour utiliser cette commande.
  finish:
    description: Commande de finish de l'inv de depart
    permission: uhc.host
    permission-message: §e§lUHC §7>> §cVous devez être host pour utiliser cette commande.
  enchant:
    description: Commande pour enchanter un item dans l'inv de depart
    permission: uhc.host
    permission-message: §e§lUHC §7>> §cVous devez être host pour utiliser cette commande.
  scenario:
    description: Commande pour afficher les scenarios
    aliases: [scen, scenarios]
  helpop:
      description: Commande de question
      aliases:
        - question
  #a:
   # description: oui
permissions:
   uhc.host:
     description: Donne accès aux commandes de host.
